import type { SqlEngine } from "./types";

/**
 * Per-engine facts the console needs on the client: which CodeMirror dialect to parse
 * with, which formatter grammar to use, how identifiers are quoted, and the built-in
 * functions worth offering in autocomplete.
 */

export interface DialectInfo {
	label: string;
	/** `@codemirror/lang-sql` dialect export name. */
	codemirror: "PostgreSQL" | "MySQL" | "MariaSQL" | "SQLite";
	/** `sql-formatter` language. */
	formatter: "postgresql" | "mysql" | "mariadb" | "sqlite";
	quote: '"' | "`";
	/** Whether the engine accepts `#` as a line comment. */
	hashComments: boolean;
	/** Postgres-style `$tag$ … $tag$` strings. */
	dollarQuotes: boolean;
	/** Backslash escapes inside string literals (MySQL default sql_mode). */
	backslashEscapes: boolean;
	functions: string[];
}

const COMMON = [
	"count",
	"sum",
	"avg",
	"min",
	"max",
	"coalesce",
	"nullif",
	"lower",
	"upper",
	"length",
	"trim",
	"replace",
	"round",
	"abs",
	"cast",
	"row_number",
	"rank",
	"dense_rank",
	"lag",
	"lead",
	"first_value",
	"last_value",
	"ntile",
];

export const DIALECTS: Record<SqlEngine, DialectInfo> = {
	postgres: {
		label: "PostgreSQL",
		codemirror: "PostgreSQL",
		formatter: "postgresql",
		quote: '"',
		hashComments: false,
		dollarQuotes: true,
		backslashEscapes: false,
		functions: [
			...COMMON,
			"greatest",
			"least",
			"now",
			"current_date",
			"current_timestamp",
			"date_trunc",
			"date_part",
			"extract",
			"age",
			"to_char",
			"to_date",
			"to_timestamp",
			"make_interval",
			"substring",
			"concat",
			"concat_ws",
			"split_part",
			"position",
			"left",
			"right",
			"lpad",
			"rpad",
			"regexp_replace",
			"regexp_matches",
			"string_agg",
			"array_agg",
			"array_length",
			"unnest",
			"json_agg",
			"jsonb_agg",
			"json_build_object",
			"jsonb_build_object",
			"jsonb_set",
			"jsonb_each",
			"jsonb_array_elements",
			"jsonb_extract_path_text",
			"jsonb_pretty",
			"to_jsonb",
			"row_to_json",
			"generate_series",
			"gen_random_uuid",
			"random",
			"floor",
			"ceil",
			"percentile_cont",
			"pg_size_pretty",
			"pg_total_relation_size",
		],
	},
	mysql: {
		label: "MySQL",
		codemirror: "MySQL",
		formatter: "mysql",
		quote: "`",
		hashComments: true,
		dollarQuotes: false,
		backslashEscapes: true,
		functions: [
			...COMMON,
			"greatest",
			"least",
			"ifnull",
			"if",
			"now",
			"curdate",
			"curtime",
			"date",
			"date_format",
			"date_add",
			"date_sub",
			"datediff",
			"timestampdiff",
			"year",
			"month",
			"day",
			"char_length",
			"substring",
			"concat",
			"concat_ws",
			"group_concat",
			"json_extract",
			"json_unquote",
			"json_object",
			"json_array",
			"json_arrayagg",
			"json_objectagg",
			"json_contains",
			"json_length",
			"json_table",
			"rand",
			"uuid",
			"floor",
			"ceil",
			"convert",
		],
	},
	mariadb: {
		label: "MariaDB",
		codemirror: "MariaSQL",
		formatter: "mariadb",
		quote: "`",
		hashComments: true,
		dollarQuotes: false,
		backslashEscapes: true,
		functions: [
			...COMMON,
			"greatest",
			"least",
			"ifnull",
			"if",
			"now",
			"curdate",
			"curtime",
			"date",
			"date_format",
			"date_add",
			"date_sub",
			"datediff",
			"timestampdiff",
			"year",
			"month",
			"day",
			"char_length",
			"substring",
			"concat",
			"concat_ws",
			"group_concat",
			"json_extract",
			"json_unquote",
			"json_object",
			"json_array",
			"json_arrayagg",
			"json_objectagg",
			"json_value",
			"json_length",
			"rand",
			"uuid",
			"floor",
			"ceil",
		],
	},
	libsql: {
		label: "libSQL",
		codemirror: "SQLite",
		formatter: "sqlite",
		quote: '"',
		hashComments: false,
		dollarQuotes: false,
		backslashEscapes: false,
		functions: [
			...COMMON,
			"total",
			"ifnull",
			"iif",
			"date",
			"time",
			"datetime",
			"julianday",
			"strftime",
			"unixepoch",
			"substr",
			"instr",
			"printf",
			"format",
			"group_concat",
			"json",
			"json_extract",
			"json_object",
			"json_array",
			"json_group_array",
			"json_group_object",
			"json_each",
			"json_tree",
			"random",
			"typeof",
			"hex",
		],
	},
};

/** Quote an identifier only when it needs it, so inserted names stay readable. */
export function quoteIdentifier(engine: SqlEngine, name: string): string {
	const q = DIALECTS[engine].quote;
	const plain = engine === "postgres" ? /^[a-z_][a-z0-9_$]*$/ : /^[A-Za-z_][A-Za-z0-9_$]*$/;
	if (plain.test(name) && !RESERVED.has(name.toLowerCase())) return name;
	return `${q}${name.split(q).join(q + q)}${q}`;
}

/** `schema.table`, omitting the schema when it is the default one. */
export function qualifiedName(
	engine: SqlEngine,
	schema: string,
	table: string,
	defaultSchema: string,
): string {
	const name = quoteIdentifier(engine, table);
	return schema === defaultSchema ? name : `${quoteIdentifier(engine, schema)}.${name}`;
}

/** Words that are never safe bare, across the four dialects. Deliberately small. */
const RESERVED = new Set([
	"select",
	"from",
	"where",
	"order",
	"group",
	"by",
	"table",
	"user",
	"limit",
	"offset",
	"join",
	"index",
	"key",
	"primary",
	"default",
	"desc",
	"asc",
	"check",
	"column",
	"constraint",
	"create",
	"drop",
	"insert",
	"update",
	"delete",
	"values",
	"to",
	"and",
	"or",
	"not",
	"null",
	"as",
	"case",
	"when",
	"end",
	"in",
	"is",
	"on",
	"all",
	"union",
	"having",
]);
