import "server-only";
import type { Database, Instance } from "@/lib/control/schema";
import { connectTenant, type TenantConnection } from "@/lib/tenant-db";
import { quoteIdentifier } from "./dialect";
import type {
	SchemaForeignKey,
	SchemaIndex,
	SchemaSnapshot,
	SchemaTable,
	SqlEngine,
} from "./types";

/**
 * Schema introspection for the SQL console, run as the tenant's own role.
 *
 * The role only sees what it has been granted, so the snapshot is exactly what that role
 * could discover with its own client — nothing here reads the instance catalog as admin.
 * One snapshot feeds the explorer, autocomplete and the assistant's context.
 */

type Record_ = Database & { instance: Instance };

const PG_SYSTEM = ["pg_catalog", "information_schema", "pg_toast"];

const str = (value: unknown) => (value === null || value === undefined ? "" : String(value));
const nullableStr = (value: unknown) =>
	value === null || value === undefined ? null : String(value);
const bool = (value: unknown) =>
	value === true || value === 1 || value === "1" || value === "t" || value === "true";
const list = (value: unknown): string[] => (Array.isArray(value) ? value.map(String) : []);

function tableKey(schema: string, name: string) {
	return `${schema}\u0000${name}`;
}

/** Groups flat rows into tables, keeping first-seen order. */
class TableMap {
	private map = new Map<string, SchemaTable>();
	ensure(schema: string, name: string, kind: SchemaTable["kind"] = "table"): SchemaTable {
		const key = tableKey(schema, name);
		let table = this.map.get(key);
		if (!table) {
			table = { schema, name, kind, columns: [], indexes: [], foreignKeys: [] };
			this.map.set(key, table);
		}
		return table;
	}
	get(schema: string, name: string) {
		return this.map.get(tableKey(schema, name));
	}
	values() {
		return [...this.map.values()].sort((a, b) =>
			a.schema === b.schema ? a.name.localeCompare(b.name) : a.schema.localeCompare(b.schema),
		);
	}
}

async function postgres(conn: TenantConnection): Promise<Omit<SchemaSnapshot, "fetchedAt">> {
	const schemas = (
		await conn.query(
			`SELECT nspname FROM pg_namespace
			 WHERE nspname <> ALL($1::text[])
			   AND nspname NOT LIKE 'pg_temp_%' AND nspname NOT LIKE 'pg_toast_temp_%'
			   AND has_schema_privilege(oid, 'USAGE')
			 ORDER BY nspname`,
			[PG_SYSTEM],
		)
	).rows.map((r) => str(r[0]));

	const tables = new TableMap();

	const columns = await conn.query(
		`SELECT n.nspname, c.relname, c.relkind, a.attname, format_type(a.atttypid, a.atttypmod),
		        NOT a.attnotnull,
		        CASE a.attidentity
		          WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
		          WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
		          ELSE pg_get_expr(d.adbin, d.adrelid) END,
		        EXISTS (SELECT 1 FROM pg_index i WHERE i.indrelid = c.oid AND i.indisprimary AND a.attnum = ANY(i.indkey))
		 FROM pg_class c
		 JOIN pg_namespace n ON n.oid = c.relnamespace
		 JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
		 LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
		 WHERE c.relkind IN ('r', 'v', 'm', 'p', 'f') AND n.nspname = ANY($1::text[])
		 ORDER BY n.nspname, c.relname, a.attnum`,
		[schemas],
	);
	for (const r of columns.rows) {
		const kind = r[2] === "v" || r[2] === "m" ? "view" : "table";
		tables.ensure(str(r[0]), str(r[1]), kind).columns.push({
			name: str(r[3]),
			type: str(r[4]),
			nullable: bool(r[5]),
			defaultValue: nullableStr(r[6]),
			isPrimaryKey: bool(r[7]),
		});
	}

	const indexes = await conn.query(
		`SELECT n.nspname, t.relname, ic.relname, ix.indisunique, ix.indisprimary,
		        ARRAY(SELECT coalesce(a.attname::text, 'expr')
		              FROM unnest(ix.indkey::int2[]) WITH ORDINALITY k(attnum, ord)
		              LEFT JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = k.attnum
		              ORDER BY k.ord)::text[]
		 FROM pg_index ix
		 JOIN pg_class t ON t.oid = ix.indrelid
		 JOIN pg_class ic ON ic.oid = ix.indexrelid
		 JOIN pg_namespace n ON n.oid = t.relnamespace
		 WHERE n.nspname = ANY($1::text[])
		 ORDER BY 1, 2, 3`,
		[schemas],
	);
	for (const r of indexes.rows) {
		tables.get(str(r[0]), str(r[1]))?.indexes.push({
			name: str(r[2]),
			unique: bool(r[3]),
			primary: bool(r[4]),
			columns: list(r[5]),
		});
	}

	const fks = await conn.query(
		`SELECT n.nspname, c.relname, con.conname,
		        ARRAY(SELECT a.attname::text FROM unnest(con.conkey) WITH ORDINALITY k(attnum, ord)
		              JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum ORDER BY k.ord)::text[],
		        fn.nspname, fc.relname,
		        ARRAY(SELECT a.attname::text FROM unnest(con.confkey) WITH ORDINALITY k(attnum, ord)
		              JOIN pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = k.attnum ORDER BY k.ord)::text[]
		 FROM pg_constraint con
		 JOIN pg_class c ON c.oid = con.conrelid
		 JOIN pg_namespace n ON n.oid = c.relnamespace
		 JOIN pg_class fc ON fc.oid = con.confrelid
		 JOIN pg_namespace fn ON fn.oid = fc.relnamespace
		 WHERE con.contype = 'f' AND n.nspname = ANY($1::text[])
		 ORDER BY 1, 2, 3`,
		[schemas],
	);
	for (const r of fks.rows) {
		tables.get(str(r[0]), str(r[1]))?.foreignKeys.push({
			name: str(r[2]),
			columns: list(r[3]),
			refSchema: str(r[4]),
			refTable: str(r[5]),
			refColumns: list(r[6]),
		});
	}

	const functions = (
		await conn.query(
			`SELECT DISTINCT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
			 WHERE n.nspname = ANY($1::text[]) ORDER BY 1`,
			[schemas],
		)
	).rows.map((r) => str(r[0]));

	return {
		engine: "postgres",
		defaultSchema: schemas.includes("public") ? "public" : (schemas[0] ?? "public"),
		schemas,
		tables: tables.values(),
		functions,
	};
}

async function mysql(
	conn: TenantConnection,
	engine: "mysql" | "mariadb",
): Promise<Omit<SchemaSnapshot, "fetchedAt">> {
	const database = str((await conn.query("SELECT DATABASE()")).rows[0]?.[0]);
	const tables = new TableMap();

	const columns = await conn.query(
		`SELECT c.TABLE_NAME, t.TABLE_TYPE, c.COLUMN_NAME, c.COLUMN_TYPE, c.IS_NULLABLE, c.COLUMN_KEY,
		        c.COLUMN_DEFAULT, c.EXTRA
		 FROM information_schema.COLUMNS c
		 JOIN information_schema.TABLES t ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
		 WHERE c.TABLE_SCHEMA = DATABASE()
		 ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION`,
	);
	for (const r of columns.rows) {
		const extra = str(r[7]);
		const fallback = nullableStr(r[6]);
		tables.ensure(database, str(r[0]), str(r[1]).includes("VIEW") ? "view" : "table").columns.push({
			name: str(r[2]),
			type: str(r[3]),
			nullable: str(r[4]).toUpperCase() === "YES",
			isPrimaryKey: str(r[5]) === "PRI",
			defaultValue: extra.toLowerCase().includes("auto_increment") ? "auto_increment" : fallback,
		});
	}

	const indexes = await conn.query(
		`SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, COLUMN_NAME
		 FROM information_schema.STATISTICS
		 WHERE TABLE_SCHEMA = DATABASE()
		 ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX`,
	);
	const byIndex = new Map<string, SchemaIndex>();
	for (const r of indexes.rows) {
		const table = tables.get(database, str(r[0]));
		if (!table) continue;
		const key = `${table.name}\u0000${str(r[1])}`;
		let index = byIndex.get(key);
		if (!index) {
			index = {
				name: str(r[1]),
				unique: Number(r[2]) === 0,
				primary: str(r[1]) === "PRIMARY",
				columns: [],
			};
			byIndex.set(key, index);
			table.indexes.push(index);
		}
		index.columns.push(str(r[3]) || "expr");
	}

	const fks = await conn.query(
		`SELECT TABLE_NAME, CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_SCHEMA, REFERENCED_TABLE_NAME,
		        REFERENCED_COLUMN_NAME
		 FROM information_schema.KEY_COLUMN_USAGE
		 WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL
		 ORDER BY TABLE_NAME, CONSTRAINT_NAME, ORDINAL_POSITION`,
	);
	const byFk = new Map<string, SchemaForeignKey>();
	for (const r of fks.rows) {
		const table = tables.get(database, str(r[0]));
		if (!table) continue;
		const key = `${table.name}\u0000${str(r[1])}`;
		let fk = byFk.get(key);
		if (!fk) {
			fk = {
				name: str(r[1]),
				columns: [],
				refSchema: str(r[3]),
				refTable: str(r[4]),
				refColumns: [],
			};
			byFk.set(key, fk);
			table.foreignKeys.push(fk);
		}
		fk.columns.push(str(r[2]));
		fk.refColumns.push(str(r[5]));
	}

	const functions = (
		await conn.query(
			"SELECT ROUTINE_NAME FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = DATABASE() ORDER BY 1",
		)
	).rows.map((r) => str(r[0]));

	return {
		engine,
		defaultSchema: database,
		schemas: [database],
		tables: tables.values(),
		functions,
	};
}

async function libsql(conn: TenantConnection): Promise<Omit<SchemaSnapshot, "fetchedAt">> {
	const schema = "main";
	const tables = new TableMap();
	const userObjects = "m.name NOT LIKE 'sqlite_%' AND m.name NOT LIKE '_litestream%'";

	const columns = await conn.query(
		`SELECT m.name, m.type, p.name, p.type, p."notnull", p.dflt_value, p.pk
		 FROM sqlite_master m JOIN pragma_table_info(m.name) p
		 WHERE m.type IN ('table', 'view') AND ${userObjects}
		 ORDER BY m.name, p.cid`,
	);
	for (const r of columns.rows) {
		tables.ensure(schema, str(r[0]), r[1] === "view" ? "view" : "table").columns.push({
			name: str(r[2]),
			type: str(r[3]) || "ANY",
			nullable: !bool(r[4]) && Number(r[6]) === 0,
			defaultValue: nullableStr(r[5]),
			isPrimaryKey: Number(r[6]) > 0,
		});
	}

	const indexes = await conn.query(
		`SELECT m.name, il.name, il."unique", il.origin, ii.name
		 FROM sqlite_master m
		 JOIN pragma_index_list(m.name) il
		 JOIN pragma_index_info(il.name) ii
		 WHERE m.type = 'table' AND ${userObjects}
		 ORDER BY m.name, il.name, ii.seqno`,
	);
	const byIndex = new Map<string, SchemaIndex>();
	for (const r of indexes.rows) {
		const table = tables.get(schema, str(r[0]));
		if (!table) continue;
		const key = `${table.name}\u0000${str(r[1])}`;
		let index = byIndex.get(key);
		if (!index) {
			index = { name: str(r[1]), unique: bool(r[2]), primary: r[3] === "pk", columns: [] };
			byIndex.set(key, index);
			table.indexes.push(index);
		}
		index.columns.push(str(r[4]) || "expr");
	}

	const fks = await conn.query(
		`SELECT m.name, fk.id, fk."from", fk."table", fk."to"
		 FROM sqlite_master m JOIN pragma_foreign_key_list(m.name) fk
		 WHERE m.type = 'table' AND ${userObjects}
		 ORDER BY m.name, fk.id, fk.seq`,
	);
	const byFk = new Map<string, SchemaForeignKey>();
	for (const r of fks.rows) {
		const table = tables.get(schema, str(r[0]));
		if (!table) continue;
		const key = `${table.name}\u0000${str(r[1])}`;
		let fk = byFk.get(key);
		if (!fk) {
			fk = {
				name: `${table.name}_fk_${str(r[1])}`,
				columns: [],
				refSchema: schema,
				refTable: str(r[3]),
				refColumns: [],
			};
			byFk.set(key, fk);
			table.foreignKeys.push(fk);
		}
		fk.columns.push(str(r[2]));
		// `to` is NULL when the reference targets the parent's primary key implicitly.
		fk.refColumns.push(str(r[4]) || "rowid");
	}

	return {
		engine: "libsql",
		defaultSchema: schema,
		schemas: [schema],
		tables: tables.values(),
		functions: [],
	};
}

export async function introspectSchema(record: Record_): Promise<SchemaSnapshot> {
	const conn = await connectTenant(record, 20_000);
	try {
		const engine = record.engine as SqlEngine;
		const snapshot =
			engine === "postgres"
				? await postgres(conn)
				: engine === "libsql"
					? await libsql(conn)
					: await mysql(conn, engine);
		return { ...snapshot, fetchedAt: Date.now() };
	} finally {
		await conn.close();
	}
}

/**
 * DDL for one table or view.
 *
 * The name is matched against a fresh snapshot before it goes anywhere near SQL — the
 * same allow-list approach as lib/tables.ts — and is passed as a bound parameter wherever
 * the engine allows one.
 */
export async function tableDdl(
	record: Record_,
	schema: string,
	name: string,
): Promise<string | null> {
	const snapshot = await introspectSchema(record);
	const table = snapshot.tables.find((t) => t.schema === schema && t.name === name);
	if (!table) return null;
	const engine = record.engine as SqlEngine;

	const conn = await connectTenant(record, 20_000);
	try {
		if (engine === "libsql") {
			const result = await conn.query(
				`SELECT sql FROM sqlite_master WHERE (name = ? OR (type = 'index' AND tbl_name = ?)) AND sql IS NOT NULL
				 ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 0 ELSE 1 END, name`,
				[table.name, table.name],
			);
			return `${result.rows.map((r) => str(r[0])).join(";\n\n")};`;
		}

		if (engine === "mysql" || engine === "mariadb") {
			const quoted = `\`${table.name.replace(/`/g, "``")}\``;
			const result = await conn.query(
				`SHOW CREATE ${table.kind === "view" ? "VIEW" : "TABLE"} ${quoted}`,
			);
			return `${str(result.rows[0]?.[1])};`;
		}

		// Postgres has no SHOW CREATE TABLE; rebuild it from the catalog the way pg_dump
		// would, using the server's own deparsers for constraints, indexes and views.
		const regclass = `"${table.schema.replace(/"/g, '""')}"."${table.name.replace(/"/g, '""')}"`;
		const qualified = `${quoteIdentifier("postgres", table.schema)}.${quoteIdentifier("postgres", table.name)}`;

		if (table.kind === "view") {
			const view = await conn.query("SELECT pg_get_viewdef($1::regclass, true)", [regclass]);
			return `CREATE VIEW ${qualified} AS\n${str(view.rows[0]?.[0]).trimEnd()}`;
		}

		const constraints = await conn.query(
			`SELECT conname, pg_get_constraintdef(oid, true) FROM pg_constraint
			 WHERE conrelid = $1::regclass AND contype IN ('p', 'u', 'f', 'c', 'x')
			 ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 ELSE 4 END, conname`,
			[regclass],
		);
		const indexes = await conn.query(
			`SELECT pg_get_indexdef(i.indexrelid) FROM pg_index i
			 WHERE i.indrelid = $1::regclass
			   AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid)
			 ORDER BY 1`,
			[regclass],
		);

		const lines = [
			...table.columns.map((column) => {
				const parts = [`  ${quoteIdentifier("postgres", column.name)} ${column.type}`];
				if (column.defaultValue?.startsWith("GENERATED")) parts.push(column.defaultValue);
				else if (column.defaultValue) parts.push(`DEFAULT ${column.defaultValue}`);
				if (!column.nullable) parts.push("NOT NULL");
				return parts.join(" ");
			}),
			...constraints.rows.map(
				(r) => `  CONSTRAINT ${quoteIdentifier("postgres", str(r[0]))} ${str(r[1])}`,
			),
		];
		const statements = [
			`CREATE TABLE ${qualified} (\n${lines.join(",\n")}\n);`,
			...indexes.rows.map((r) => `${str(r[0])};`),
		];
		return statements.join("\n\n");
	} finally {
		await conn.close();
	}
}

/** Compact, model-friendly text form of a snapshot, for the assistant's context. */
export function schemaAsText(snapshot: SchemaSnapshot, maxChars = 24_000): string {
	const lines: string[] = [];
	for (const table of snapshot.tables) {
		const name =
			table.schema === snapshot.defaultSchema ? table.name : `${table.schema}.${table.name}`;
		const columns = table.columns.map((c) => {
			const flags = [c.isPrimaryKey ? "pk" : "", c.nullable || c.isPrimaryKey ? "" : "not null"]
				.filter(Boolean)
				.join(" ");
			return `${c.name} ${c.type}${flags ? ` ${flags}` : ""}`;
		});
		lines.push(`${table.kind} ${name} (${columns.join(", ")})`);
		for (const fk of table.foreignKeys) {
			lines.push(
				`  fk ${fk.columns.join(", ")} -> ${fk.refSchema === snapshot.defaultSchema ? "" : `${fk.refSchema}.`}${fk.refTable}(${fk.refColumns.join(", ")})`,
			);
		}
		for (const index of table.indexes.filter((i) => !i.primary)) {
			lines.push(
				`  ${index.unique ? "unique index" : "index"} ${index.name} (${index.columns.join(", ")})`,
			);
		}
	}
	const text = lines.join("\n");
	return text.length > maxChars ? `${text.slice(0, maxChars)}\n… (schema truncated)` : text;
}
