import "server-only";
import { asc, eq } from "drizzle-orm";
import { adminConnectionString, connectionHost } from "@/lib/connection";
import { db } from "@/lib/control/db";
import { type Instance, instances, nodes } from "@/lib/control/schema";
import { encryptSecret, generatePassword } from "@/lib/crypto";
import { dokployGet, dokployPost } from "@/lib/dokploy/client";
import { ENGINE_CONFIG, type Engine } from "@/lib/engines/types";
import { env } from "@/lib/env";
import { newId } from "@/lib/id";
import { LIMITS } from "@/lib/limits";
import { removeSniRoute, writeSniRoute } from "./sni";

/**
 * Container lifecycle for engines whose tenants get a machine of their own.
 *
 * For a shared engine, placement picks an instance that already exists and provisioning
 * is one `CREATE DATABASE`. Here the instance *is* the tenant: it has to be created,
 * started, waited for, and routed to before there is anything to hand back — and torn
 * down again when the database is deleted. The `instances` row is therefore created and
 * destroyed alongside the database rather than being long-lived infrastructure.
 *
 * The honest cost: this takes tens of seconds, not the ~200ms a shared engine takes.
 * Pulling an image and scheduling a container has a floor that no amount of care removes,
 * and `tookMs` reports the real number rather than hiding it.
 */

/** How long to wait for a freshly scheduled container to answer. */
const READY_TIMEOUT_MS = 120_000;
const READY_POLL_MS = 2_000;

export class DedicatedProvisionError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "DedicatedProvisionError";
	}
}

/**
 * Image for a dedicated container.
 *
 * Redis runs a blaze-built image rather than the stock one because the policy that makes
 * it safe to hand to a stranger — TLS-only listener, memory quota, a `default` user that
 * cannot rewrite either — has to be applied at startup, and Dokploy overrides
 * ENTRYPOINT/CMD for database services and ignores its own `command` field. Baking it
 * into the image is the only place the settings survive.
 */
function imageFor(engine: Engine): string {
	if (engine === "redis") return env.BLAZE_REDIS_IMAGE;
	return ENGINE_CONFIG[engine].image;
}

/** Per-container environment. Read by the image's entrypoint at startup. */
function containerEnv(engine: Engine, adminPassword: string): string {
	if (engine !== "redis") return "";
	return [
		`BLAZE_ADMIN_PASSWORD=${adminPassword}`,
		`BLAZE_MAXMEMORY=${LIMITS.REDIS_MEMORY_BYTES}`,
	].join("\n");
}

async function firstNodeId(): Promise<string> {
	const [node] = await db.select().from(nodes).orderBy(asc(nodes.createdAt)).limit(1);
	if (!node)
		throw new DedicatedProvisionError("No node registered — run scripts/bootstrap-instance.ts");
	return node.id;
}

/**
 * Create, start and route a container for one tenant.
 *
 * Ordering is chosen so that every failure leaves something a human can find and delete
 * rather than an invisible orphan: the container exists in Dokploy before anything points
 * at it, and the `instances` row — the thing blaze itself uses to find the container
 * again — is written only once the container answers.
 */
export async function allocateDedicatedInstance(options: {
	engine: Engine;
	databaseId: string;
	slug: string;
	/** The password the tenant will connect with, already generated by the caller. */
	tenantPassword: string;
}): Promise<Instance> {
	const { engine, databaseId, slug, tenantPassword } = options;
	const config = ENGINE_CONFIG[engine];
	const idKey = config.dokployIdKey;

	if (!env.DOKPLOY_ENVIRONMENT_ID) {
		throw new DedicatedProvisionError(
			`DOKPLOY_ENVIRONMENT_ID is not set; ${engine} needs a container per database.`,
		);
	}

	const adminPassword = generatePassword();
	const host = connectionHost(engine, slug, databaseId);

	// Dokploy appends its own suffix to whatever name it is given, so the real service
	// name has to be read back rather than predicted.
	const created = await dokployPost<Record<string, unknown>>(`${engine}.create`, {
		name: `blz-${engine}-${databaseId.replace(/^db_/, "")}`,
		environmentId: env.DOKPLOY_ENVIRONMENT_ID,
		databasePassword: tenantPassword,
		dockerImage: imageFor(engine),
		description: `blaze tenant ${slug} (${databaseId})`,
	});

	const serviceId = created[idKey] as string | undefined;
	if (!serviceId) {
		throw new DedicatedProvisionError(`Dokploy did not return ${idKey} for the new container`);
	}

	try {
		const environment = containerEnv(engine, adminPassword);
		if (environment) {
			await dokployPost(`${engine}.saveEnvironment`, { [idKey]: serviceId, env: environment });
		}

		/*
		 * Deliberately no `saveExternalPort`. A dedicated container is reached through the
		 * SNI router on the engine's single shared port, so it never publishes one of its
		 * own — which is what keeps the product from being capped at the number of free
		 * ports on the host, the ceiling `lib/connection.ts` exists to avoid.
		 */
		await dokployPost(`${engine}.deploy`, { [idKey]: serviceId });

		const detail = await dokployGet<Record<string, unknown>>(`${engine}.one`, {
			[idKey]: serviceId,
		});
		const appName = detail.appName as string | undefined;
		if (!appName) {
			throw new DedicatedProvisionError("Dokploy did not report the container's service name");
		}

		const adminUrl = adminConnectionString(
			engine,
			appName,
			config.port,
			"blazeadmin",
			encryptSecret(adminPassword),
		);

		await waitUntilReady(engine, adminUrl);

		// Routed only once it answers, so the hostname never resolves to a container that
		// is still starting.
		await writeSniRoute({
			host,
			backend: appName,
			port: config.port,
			// One entrypoint per engine, named after the same prefix the hostname uses.
			entryPoint: config.hostPrefix,
		});

		const [instance] = await db
			.insert(instances)
			.values({
				id: newId("inst"),
				nodeId: await firstNodeId(),
				engine,
				tenancy: "dedicated",
				version: imageFor(engine),
				internalHost: appName,
				port: config.port,
				adminUser: "blazeadmin",
				adminPasswordEnc: encryptSecret(adminPassword),
				dokployServiceId: serviceId,
				// One tenant, by definition — placement must never put a second here.
				capacity: 1,
				databaseCount: 0,
				status: "active",
			})
			.returning();

		return instance;
	} catch (error) {
		// The container is the expensive, visible artefact; leaving one behind for every
		// failed create would quietly fill the box.
		await dokployPost(`${engine}.remove`, { [idKey]: serviceId }).catch(() => {});
		await removeSniRoute(host).catch(() => {});
		throw error;
	}
}

/**
 * Destroy a tenant's container and retire its row. Safe to retry.
 *
 * The row is marked `offline` rather than deleted: deleting a database is a *soft* delete,
 * so its row survives and still references this instance. Placement only ever considers
 * `active` instances, so an offline one is inert — and keeping it means the audit trail of
 * a deleted database still resolves to where it actually lived.
 */
export async function releaseDedicatedInstance(instance: Instance, host: string): Promise<void> {
	const idKey = ENGINE_CONFIG[instance.engine].dokployIdKey;

	// Route first: stop sending traffic before the destination disappears.
	await removeSniRoute(host);

	if (instance.dokployServiceId) {
		await dokployPost(`${instance.engine}.remove`, { [idKey]: instance.dokployServiceId });
	}

	await db
		.update(instances)
		.set({ status: "offline", databaseCount: 0 })
		.where(eq(instances.id, instance.id));
}

/**
 * Write a rotated password into the container's service definition.
 *
 * `resetPassword` changes the running server, which takes effect at once but lives only
 * in memory. Dokploy starts the container from a definition that still carries the old
 * password, so without this a restart would silently resurrect the credential the user
 * just rotated away from — the worst kind of security bug, one that looks fixed.
 *
 * The container is deliberately *not* redeployed: that would restart it and drop the
 * tenant's data for an in-memory engine. The two are consistent from the next restart on,
 * which is exactly when the stored value starts to matter.
 */
export async function persistDedicatedPassword(
	instance: Instance,
	password: string,
): Promise<void> {
	const idKey = ENGINE_CONFIG[instance.engine].dokployIdKey;
	if (!instance.dokployServiceId) return;

	await dokployPost(`${instance.engine}.update`, {
		[idKey]: instance.dokployServiceId,
		databasePassword: password,
	});
}

/** Poll until the container answers, or give up with a diagnosable error. */
async function waitUntilReady(engine: Engine, adminUrl: string): Promise<void> {
	const { provisionRedisDatabase } = await import("./redis");
	const deadline = Date.now() + READY_TIMEOUT_MS;
	let lastError: unknown;

	while (Date.now() < deadline) {
		try {
			if (engine === "redis") {
				await provisionRedisDatabase({ adminUrl, dbName: "", roleName: "", password: "" });
				return;
			}
			return;
		} catch (error) {
			lastError = error;
			await new Promise((resolve) => setTimeout(resolve, READY_POLL_MS));
		}
	}

	const detail = lastError instanceof Error ? lastError.message : String(lastError);
	throw new DedicatedProvisionError(
		`Container did not become ready within ${READY_TIMEOUT_MS / 1000}s: ${detail}`,
	);
}
