/**
 * SQL identifiers cannot be passed as bind parameters, so database and role names are
 * interpolated into DDL as text. Every name blaze uses is generated by `lib/id.ts` and
 * never taken from user input — but "generated upstream" is an assumption that survives
 * exactly until someone adds a code path that forgets, so it is checked here at the point
 * of use rather than trusted.
 *
 * The allowed shape is deliberately narrower than what Postgres permits: lowercase
 * alphanumerics and underscores only, must start with a letter, 63 bytes max (Postgres's
 * NAMEDATALEN limit, beyond which it silently truncates — and a silent truncation on a
 * database name is a collision waiting to happen).
 */

const SAFE = /^[a-z][a-z0-9_]{0,62}$/;

export class UnsafeIdentifierError extends Error {
	constructor(kind: string, value: string) {
		super(`Refusing to use ${kind} ${JSON.stringify(value)} in DDL: unsafe identifier`);
		this.name = "UnsafeIdentifierError";
	}
}

export function assertSafeIdentifier(kind: string, value: string): string {
	if (!SAFE.test(value)) throw new UnsafeIdentifierError(kind, value);
	return value;
}

/** Double-quote a checked identifier for Postgres. */
export function quoteIdent(kind: string, value: string): string {
	return `"${assertSafeIdentifier(kind, value)}"`;
}

/** Backtick-quote a checked identifier for MySQL/MariaDB. */
export function quoteIdentMysql(kind: string, value: string): string {
	return `\`${assertSafeIdentifier(kind, value)}\``;
}

/**
 * Escape a password for use in a SQL string literal.
 *
 * Passwords come from `generatePassword`, whose alphabet contains no quotes — but
 * `CREATE ROLE ... PASSWORD` cannot take a bind parameter either, so this doubles single
 * quotes rather than relying on that alphabet staying the same forever.
 */
export function quoteLiteral(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}
