import "server-only";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { env } from "@/lib/env";

/**
 * Per-tenant TCP routes for blaze's own SNI router.
 *
 * Dedicated engines give every tenant its own container, so the *hostname* selects the
 * tenant: `myapp-x7f2.redis.blaze.crafter.run`. A router in front of them reads the TLS
 * SNI field and forwards the raw connection to the right container.
 *
 * Two decisions worth stating, because both were arrived at the hard way:
 *
 * - **Its own router, not Dokploy's Traefik.** Dokploy's proxy fronts every other site on
 *   the box; adding a TCP entrypoint means editing its static config and restarting it,
 *   which is an outage for unrelated projects every time blaze changes a port. `blaze-sni`
 *   owns exactly one port and can be restarted freely.
 *
 * - **TLS passthrough, not termination.** The router never sees the certificate or the
 *   plaintext; it matches on SNI and splices the bytes through. That keeps the connection
 *   encrypted end to end, into the tenant's container, and means the router needs no
 *   certificate of its own — the alternative would require a wildcard certificate and
 *   would decrypt every tenant's traffic in a shared process.
 *
 * The router watches this directory and hot-reloads, so adding a tenant is a file write
 * and never a restart. In exchange this module must never emit a file the router cannot
 * parse: a malformed route would be ignored, and one bad write would take down routing
 * for every tenant in the same file. One file per tenant keeps that blast radius at one.
 */

/** Only ever a slug and an id, both from a restricted alphabet — asserted, not assumed. */
const SAFE_HOST = /^[a-z0-9][a-z0-9.-]{0,252}[a-z0-9]$/;
const SAFE_BACKEND = /^[a-z0-9][a-z0-9_-]{0,62}$/;

function dynamicDir(): string {
	return env.SNI_DYNAMIC_DIR;
}

function routePath(host: string): string {
	// The hostname is already asserted safe, and a bare label cannot contain a separator.
	return join(dynamicDir(), `${host}.yml`);
}

/**
 * Publish the route for one dedicated tenant.
 *
 * Idempotent: the same tenant written twice produces the same file, so a retried
 * provision does not accumulate duplicate routers.
 */
export async function writeSniRoute(options: {
	/** Public hostname, e.g. `myapp-x7f2.redis.blaze.crafter.run`. */
	host: string;
	/** Container to forward to — the Docker service name on the shared network. */
	backend: string;
	port: number;
	/** Traefik entrypoint, one per engine. */
	entryPoint: string;
}): Promise<void> {
	const { host, backend, port, entryPoint } = options;

	if (!SAFE_HOST.test(host)) throw new Error(`Refusing to route unsafe hostname: ${host}`);
	if (!SAFE_BACKEND.test(backend)) throw new Error(`Refusing to route to unsafe backend`);
	if (!Number.isInteger(port) || port < 1 || port > 65535) {
		throw new Error(`Refusing to route to invalid port: ${port}`);
	}

	const name = host.replace(/\./g, "-");

	/*
	 * Priority beats the catch-all in `00-fallback.yml`, which exists so that a client
	 * arriving with no SNI — or an SNI for a tenant that has been deleted — is closed
	 * immediately instead of hanging until its own timeout.
	 */
	const document = `# Generated by blaze. Do not edit: rewritten on provision, deleted on teardown.
tcp:
  routers:
    ${name}:
      entryPoints: ["${entryPoint}"]
      rule: "HostSNI(\`${host}\`)"
      priority: 100
      tls:
        passthrough: true
      service: "${name}"
  services:
    ${name}:
      loadBalancer:
        servers:
          - address: "${backend}:${port}"
`;

	await mkdir(dynamicDir(), { recursive: true });
	await writeFile(routePath(host), document, "utf8");
}

/**
 * Withdraw a tenant's route.
 *
 * Missing is success: teardown has to be safe to retry, and a route that is already gone
 * is the state the caller wanted. Any other failure propagates — silently leaving a route
 * pointing at a destroyed container would send the next tenant's traffic nowhere.
 */
export async function removeSniRoute(host: string): Promise<void> {
	if (!SAFE_HOST.test(host)) throw new Error(`Refusing to remove unsafe hostname: ${host}`);
	await rm(routePath(host), { force: true });
}
